Adding band structure parser for cp2k version 8.1.
aiidateam/aiida-cp2k pull request #126
Opened 2021-02-15 06:21 UTC by hdsassnick

Hello,

I would firstly like to thank you for the work and effort developing the AiiDA-plugin for cp2k.
It is a great addition to the AiiDA-library and facilitates my work a lot.

I noticed that for the new version 8.1 of cp2k the output format of the band structure has changed and is incompatible with previous versions.
I would like to contribute an adaption of the advanced-output parser which should work with the most recent versions of cp2k
but still keeps the downwards compatibility to older versions of the program.

I would be very happy if the snippet of additional code can be helpful.
This is my first pull request. Apologies if I hadn't done it completely correctly.

Best wishes,
Holger

2021-02-16 09:10 UTC, yakutovicha commented
Hey @hdsassnick, thanks a lot. 

> I would be very happy if the snippet of additional code can be helpful.

No worries, I think you did a great job.

Before I start reviewing the PR, can you please fix the pre-commit issues? It basically just adds two empty lines, see [here](https://github.com/aiidateam/aiida-cp2k/pull/126/checks?check_run_id=1901111007)

2021-02-17 06:39 UTC, hdsassnick commented
Hi, should work now.

2021-02-23 19:48 UTC, hdsassnick commented
Hi,

I was just wondering if there was any news concerning the review of the pull request.

2021-02-24 01:00 UTC, yakutovicha requested changes
Hey @hdsassnick, sorry for the long wait.

I had a closer look at your implementation and I have a couple of suggestions.  Generally, I think it would be a good idea to reuse the code that is there already. For instance, the parts of the code that don't work with the 8.1 version of CP2K are:

https://github.com/aiidateam/aiida-cp2k/blob/60d518309055f9731360db81ead3b2119a154b0f/aiida_cp2k/utils/parser.py#L301

and

https://github.com/aiidateam/aiida-cp2k/blob/60d518309055f9731360db81ead3b2119a154b0f/aiida_cp2k/utils/parser.py#L312-L317

Herein, I think it would be better to modify the `_parse_bands` function as follows

```python

def _parse_band_before81(band_lines):
    put the old code here

def _parse_band_after81(band_lines):
    put the new code here

def _parse_bands(lines, n_start, cp2k_version):
    if cp2k_version < 8.1:
        pattern = re.compile(".*?Nr.*?Spin.*?K-Point.*?", re.DOTALL)
        parse_band_function = _parse_band_before81
    else:
        pattern = re.compile(".*?Point.*?Spin.*?", re.DOTALL) # didn't try it myself
        parse_band_function = _parse_band_after81

```

I think this approach allows us to write shorter and clearer code.

Let me know if you agree.

2021-02-24 08:34 UTC, hdsassnick commented
Hi,
Thank you very much for the suggestions. Indeed I forgot to remove some print statements that I just included for testing the function, thank you for pointing that out.
I think the differences between the two functions is actually a bit larger, e.g. the number of bands is not printed at the head of each k-point in the new cp2k version. 
Thus, the current function for cp2k v8.1 is checking line-by-line if an eigenvalue needs to be added to the list. In contrast to that, in cp2k v7.1 the number of eigenvalues is known beforehand, and this information is then being used to add all eigenvalues in one go.
That is why I have a few doubts that merging the two versions of "_parse_bands" would simplify the code by a large extent. Nevertheless, I will give it a try.

2021-02-24 12:41 UTC, hdsassnick commented
Hi @yakutovicha ,

I tried to implement your suggestions. I'm not sure if I did it the way you intended.
Could you please have another look at the implementation?

2021-02-25 00:10 UTC, yakutovicha commented on test/test_parser.py
> +"""Test writing structures to xyz format"""
```suggestion
"""Test parsing band structure."""
```

2021-02-25 00:10 UTC, yakutovicha commented on test/test_parser.py
> +"""Test parsing band structure."""
```suggestion
"""Test output parser."""
```

2021-02-25 00:11 UTC, yakutovicha commented on aiida_cp2k/utils/parser.py
> +def _parse_one_band_after_81(lines, line_n):
```suggestion
def _parse_bands_cp2k_greater_81(lines, line_n):
```

2021-02-25 00:11 UTC, yakutovicha commented on aiida_cp2k/utils/parser.py
> +def _parse_one_band_before_81(lines, line_n):
```suggestion
def _parse_bands_cp2k_lower_81(lines, line_n):
```

2021-02-25 00:12 UTC, yakutovicha commented on aiida_cp2k/utils/parser.py
> +        parse_one_band = _parse_one_band_before_81
```suggestion
        parse_one_band = _parse_bands_cp2k_lower_81
```

2021-02-25 00:13 UTC, yakutovicha commented on aiida_cp2k/utils/parser.py
> +        parse_one_band = _parse_one_band_after_81
```suggestion
        parse_one_band = _parse_bands_cp2k_greater_81
```

2021-02-25 00:18 UTC, yakutovicha commented
> Hi @yakutovicha ,
> 
> I tried to implement your suggestions. I'm not sure if I did it the way you intended.
> Could you please have another look at the implementation?

@hdsassnick I decided to continue the development a little bit on my own - sorry for that. I just thought that it would be easier for me to implement what I had in mind directly rather than explain what I actually meant.

> ... e.g. the number of bands is not printed at the head of each k-point in the new cp2k version.

I think that is a pretty minor difference which could be resolved by employing `try...except` - please have a look in the code.

> That is why I have a few doubts that merging the two versions of "_parse_bands" would simplify the code by a large extent.

Let me know what you think of the current implementation.

2021-02-25 13:20 UTC, hdsassnick commented
Hi @yakutovicha ,
Thanks so much! This new version looks fantastic.
I just would have a small addition concerning the case when labels are not given (I also overlooked this detail in my first commit, sorry).

2021-02-26 16:06 UTC, yakutovicha commented on test/test_parser.py
> +# AiiDA-CP2K is hosted on GitHub at https://github.com/aiidateam/aiida-cp2k        #
```suggestion
# AiiDA-CP2K is hosted on GitHub at https://github.com/aiidateam/aiida-cp2k  #
```

2021-02-26 16:10 UTC, yakutovicha commented on test/test_parser.py
> +    # Test parsing bands in the the output of CP2K 8.1
```suggestion
    """Test parsing bands in the the output of CP2K 8.1"""
```

2021-02-26 16:11 UTC, yakutovicha commented on test/test_parser.py
> +    # Test parsing bands in the the output of CP2K 5.1
```suggestion
    """Test parsing bands in the output of CP2K 5.1"""

```

2021-02-26 16:32 UTC, yakutovicha approved these changes
alright, I think this is ready to go.

Thanks, @hdsassnick for your contribution and for using the plugin. You are very welcome to create issues if something isn't working correctly or issues/PRs in case you want to suggest further improvements!

2021-02-26 16:35 UTC, merged

2021-02-26 16:36 UTC, yakutovicha commented
This will be available in the next minor release of the plugin.