Adding a extra condition to restart_incomplete_calcution
aiidateam/aiida-cp2k pull request #179
Opened 2022-12-01 14:27 UTC by AndresOrtegaGuerrero

The new conditions ask for the end of SCF inner cycle with "Total energy:", This guarantees that there is *.wfn file in the directory

2022-12-01 16:34 UTC, yakutovicha reviewed
Please fix the test and request my review then 👍

2022-12-02 09:05 UTC, AndresOrtegaGuerrero commented
I restored the initial conditions (remove my changes) , but somehow is not working , I get an error 402 (which i dont find). I assume now it should pass the test in github, yet i need to work on the solution

2022-12-02 11:08 UTC, AndresOrtegaGuerrero commented
The issue seems that the `example_base_failed_restart.py` , checks if the process exit_status is `400`, however, there could be the case that in the first restart it successfully completes the calculation, then the exit code is `0` for the workchain , or is `402` which means that 2 attempts were not enough to complete the simulations. I include a modification to check the first calcjob to check if the restart is handled.

2022-12-05 16:07 UTC, yakutovicha requested changes
Ok, almost good to go. Just a few minor suggestions.

2022-12-05 16:07 UTC, yakutovicha commented on examples/workchains/example_base_energy_restart.py
> +                "WALLTIME": "00:00:05",  # Can't even do one geo opt step.
```suggestion
                "WALLTIME": "00:00:05",  # Not enough time to converge an SCF loop
```

2022-12-05 16:07 UTC, yakutovicha commented on examples/workchains/example_base_failed_restart.py
> +        # "withmpi": True,  # A trick to put the kill below before raspa command.
```suggestion
```

2022-12-05 16:07 UTC, yakutovicha commented on examples/workchains/example_base_failed_restart.py
> +        ],  # Kill the calculation after 5 seconds, to test restart.
```suggestion
        ],  # Kill the calculation after 5 seconds to test the restart failure.
```

2022-12-06 12:59 UTC, yakutovicha commented on examples/workchains/example_base_failed_restart.py
> +        ],  # Kill the calculation after 5 seconds to test the restart failure.
```suggestion
        ],  # Kill the calculation after 1 second to test the restart failure.
```

2022-12-06 13:01 UTC, yakutovicha approved these changes
looks good 👍

2022-12-06 13:22 UTC, merged